server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: codewitharjun12
    url: jdbc:mysql://localhost:3306/crudapp
    username: root
  jpa:
    hibernate:
      ddl-auto: 'update '
    show-sql: true